version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kharkivgo
    ports:
      - '5432:5432'
    volumes:
      - kharkivgo_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - kharkivgo_redis_data:/data

volumes:
  kharkivgo_pg_data:
  kharkivgo_redis_data:
